# Generated by Django 5.2.4 on 2025-07-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiftEnvironmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('application_id', models.IntegerField()),
                ('battery', models.IntegerField(blank=True, null=True)),
                ('cellular_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dev_eui', models.CharField(max_length=32)),
                ('device_name', models.CharField(max_length=100)),
                ('gateway_time', models.DateTimeField()),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField()),
            ],
        ),
    ]
