# Generated by Django 5.2.4 on 2025-07-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlift', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiftControlLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('application_id', models.IntegerField()),
                ('cellular_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dev_eui', models.CharField(max_length=32)),
                ('device_name', models.CharField(max_length=100)),
                ('gateway_time', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('gpio_input_1', models.IntegerField(blank=True, null=True)),
                ('gpio_input_2', models.IntegerField(blank=True, null=True)),
                ('gpio_input_4', models.IntegerField(blank=True, null=True)),
                ('gpio_output_1', models.IntegerField(blank=True, null=True)),
                ('gpio_output_2', models.IntegerField(blank=True, null=True)),
                ('gpio_counter_3', models.IntegerField(blank=True, null=True)),
                ('adv_1', models.FloatField(blank=True, null=True)),
                ('adv_1_avg', models.FloatField(blank=True, null=True)),
                ('adv_1_max', models.FloatField(blank=True, null=True)),
                ('adv_1_min', models.FloatField(blank=True, null=True)),
                ('adv_2', models.FloatField(blank=True, null=True)),
                ('adv_2_avg', models.FloatField(blank=True, null=True)),
                ('adv_2_max', models.FloatField(blank=True, null=True)),
                ('adv_2_min', models.FloatField(blank=True, null=True)),
                ('raw_payload', models.JSONField()),
            ],
        ),
    ]
