# Generated by Django 5.2.4 on 2025-07-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlift', '0002_liftcontrollog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiftDoorEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('application_id', models.IntegerField()),
                ('cellular_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dev_eui', models.CharField(max_length=32)),
                ('device_name', models.CharField(max_length=100)),
                ('gateway_time', models.DateTimeField()),
                ('text', models.TextField()),
                ('event_type', models.CharField(choices=[('open', 'Open'), ('close', 'Close')], max_length=10)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField()),
            ],
        ),
    ]
