# Generated by Django 5.2.4 on 2025-07-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlift', '0004_liftoccupancylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyMeterLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('device_name', models.CharField(max_length=100)),
                ('dev_eui', models.CharField(max_length=32)),
                ('gateway_time', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('system_kw', models.FloatField(blank=True, null=True)),
                ('system_kva', models.FloatField(blank=True, null=True)),
                ('system_kvar', models.FloatField(blank=True, null=True)),
                ('system_pf', models.FloatField(blank=True, null=True)),
                ('frequency', models.FloatField(blank=True, null=True)),
                ('phase1_volts', models.FloatField(blank=True, null=True)),
                ('phase1_amps', models.FloatField(blank=True, null=True)),
                ('phase1_kw', models.FloatField(blank=True, null=True)),
                ('phase2_volts', models.FloatField(blank=True, null=True)),
                ('phase2_amps', models.FloatField(blank=True, null=True)),
                ('phase2_kw', models.FloatField(blank=True, null=True)),
                ('phase3_volts', models.FloatField(blank=True, null=True)),
                ('phase3_amps', models.FloatField(blank=True, null=True)),
                ('phase3_kw', models.FloatField(blank=True, null=True)),
                ('phase1_pf', models.FloatField(blank=True, null=True)),
                ('phase2_pf', models.FloatField(blank=True, null=True)),
                ('phase3_pf', models.FloatField(blank=True, null=True)),
                ('raw_payload', models.JSONField()),
            ],
        ),
    ]
